language: python
python:
    - "2.7"
    - "3.4"
install:
    - pip install .
    - pip install flake8 nose coverage
script:
    - flake8 -v pitch tests
    - cd tests
    # Unit Tests & Coverage
    - nosetests -v --with-coverage --cover-package=pitch
    # Integration tests
    - ./run-public-api-tests.py   
    # Check documentation
    - cd ..
    - cp README.md README.md.dist
    - ./generate-documentation.py
    - diff README.md README.md.dist

  
