language: python
python:
    - "3.6"
install:
    - pip install .
    - pip install flake8 nose coverage
script:
    - flake8 -v pitch tests
    # Unit Tests & Coverage
    - nosetests -v --with-coverage --cover-package=pitch tests/
    # Integration tests
    - ./.ci/run-integration-tests.sh
    # Check documentation
#    - cd ..
#    - cp README.md README.md.dist
#    - ./generate-documentation.py
#    - diff README.md README.md.dist

