language: python
python:
    - "2.7"
    - "3.4"
install:
    - pip install .
    - pip install flake8
script:
    - flake8 pitch tests
    - cd tests; python -m unittest discover
    - cd tests; ./run-public-api-tests.py   

  
